# CREAR UNA COLLECION
ansible-galaxy collection init ocantoran.c1

# CREAR UN FICHERO tar.gz PARA QUE SE PUEDA INSTALAR ESE PLAYBOOK
ansible-galaxy collection build

# INSTALAR FICHERO
ansible-galaxy collection installl ocantoran.c1-1.0.0.tar.gz
 --force

 # UTILIZAR UNA COLLECION
---
- name: Probar mi coleccion
  hosts: debian1
  collections:
    - ocantoran.c1
  tasks: 
    - name: Llamar al modulo
      ocantoran.c1.modulo:
        texto: Voy a probar mi collection
      register: v1

    - name: Visualizar la salida
      ansible.builtin.debug:
         msg: "{{ v1 }}"



