---
- name: Trabajar con JUNJA2. Montar APACHE
  hosts:
    - debian1
  vars:
    software: tomcat
    version: 9
  tasks:
    - name: Instalar {{ software }}
      ansible.builtin.apt:
        - name: "{{ software }}"
          state: present

    - name: copiar resultado
      ansible.builtin.template:
        src: operadores.j2
        dest: /tmp/resultado.txt
