---
- name: Trabajar con JINJA2. Montar APACHE
  hosts:
    - debian1
    - rocky1
  tasks:
    - name: Instalar apache
      ansible.builtin.apt:
        name: apache2
        state: present
      when: ansible_distribution == 'Debian'

    - name: Instalar apache en Rocky
      ansible.builtin.yum:
        name: httpd
        state: present
      when: ansible_distribution == 'Rocky'

    - name: Copiar pagina WEB
      ansible.builtin.template:
        src: condicionales.j2
        dest: /var/www/html/index.html

    - name: Arrancar apache
      ansible.builtin.service:
        name: apache2
        state: started
      when: ansible_distribution == 'Debian'

    - name: Arrancar apache
      ansible.builtin.service:
        name: httpd
        state: started
      when: ansible_distribution == 'Rocky'
