---
- name: Descargar imagen Docker
  hosts: rhel
  tasks:
    - name: Descargar TOMCAT
      community.docker.docker_image:
        name: tomcat
        source: pull

    ################### CAMBIAR EL TAG A UNA IMAGEN ####################

    - name: Etiquetar de nuevo el tomcat
      community.docker.docker_image:
        name: tomcat
        repository: mi-tomcat
        source: local
