# PERMITEN REALIZAR DISTINTAS OPERACIONES COMO PUEDEN SER
# - CONVERSION
# - TRANSFORMACION
# - EXTRACIONES
# - MANIPULAR DATOS
# - ETC..

# NOTA: LOS FILTROS SE EJECUTAN EN EL CONTROLLER NO EN LA MAQUINA REMOTA
# SE USA EL SIMBOLO "|" PARA INDICARLOS

---
name: Ejemplos varios de filtros
hosts: rhel1
vars:
  cadena: "hola"
  numero: 10.1
  verdad: true
  lista:
    - pepe
    - juan
    - antonio
  lista1: ["pepe", "juan", antonio]
  diccionario:
    nombre: juan
    edad: 27
tasks:
  - name: Averiguar el tipo de una variable
    ansible.builtin.debug:
      var: cadena | type_debug
  ################################# CONVERTIR DATOS ##################

  - name: numero antes de convertir
    ansible.builtin.debug:
      var: numero

  - name: Convertir a cadena
    ansible.builtin.debug:
      var: numero | string

  - name: Convertira entero
    ansible.builtin.debug:
      var: numero | int

  - name: Ver numero de version de SO
    ansible.builtin.debug:
      msg: "{{ ansible_facts['distribution_version'] }}"
    when: ansible_distribution_version | int > 10

  #################################### CADENAS #############################
  - name: Cadenas mayusculas
    vars:
      cadena: "esto es una cadena"
    ansible.builtin.debug:
      var: cadena | upper

  - name: Cadenas minusculas
    vars:
      cadena: "esto es una cadena"
    ansible.builtin.debug:
      var: cadena | lower

  - name: Remplazar
    vars:
      cadena: "esto es una cadena"
    ansible.builtin.debug:
      var: cadena | replace("e","*")

  - name: longitud de la cadena
    vars:
      cadena: "esto es una cadena"
    ansible.builtin.debug:
      var: cadena | length
  ######################################## NUMEROS ###################################

  - name: potencia
    vars:
      numero: 10.40
    ansible.builtin.debug:
      var: numero | pow(4)

  - name: raiz cuadrada
    vars:
      numero: 10.40
    ansible.builtin.debug:
      var: numero | root()

  - name: redondeada
    vars:
      numero: 10.40
    ansible.builtin.debug:
      var: numero | round()

  - name: redondeado y numero random entre 0 y el numero de la variable
    vars:
      numero: 10.40
    ansible.builtin.debug:
      var: numero | int | random

  ###################### LISTAS ###########################33
  - name: Valor menor numero
    vars:
      lista_nuero:
        - 2
        - 10
        - 9
        - 1
      lista_cadena:
        - Pedro
        - Juan
        - Rosa
        - Antonio
      cadena: "esto es una cadena"
    ansible.builtin.debug:
      msg: "{{ lista_numero | min  }} -- {{ lista_numero | max }}"

  - name: Valor menor cadena
    vars:
      lista_nuero:
        - 2
        - 10
        - 9
        - 1
      lista_cadena:
        - Pedro
        - Juan
        - Rosa
        - Antonio
      cadena: "esto es una cadena"
    ansible.builtin.debug:
      msg: "{{ lista_cadena: | min  }} -- {{ lista_cadena: | max }}"

  - name: Unir elementos de una lista
    vars:
      lista_nuero:
        - 2
        - 10
        - 9
        - 1
      lista_cadena:
        - Pedro
        - Juan
        - Rosa
        - Antonio
      cadena: "esto es una cadena"
    ansible.builtin.debug:
      msg: "{{ lista_cadena | join(',') }}"

  - name: Convertir cadena en lista
    vars:
      lista_nuero:
        - 2
        - 10
        - 9
        - 1
      lista_cadena:
        - Pedro
        - Juan
        - Rosa
        - Antonio
      cadena: "esto es una cadena"
    ansible.builtin.debug:
      msg: "{{ lista_cadena | split() }}"
