---
- name: Probar vault creando usuarios y claves
  hosts: debian1
  vars_files: vars/usuarios.yml
  tasks:
    - name: Crear usuarios
      ansible.builtin.user:
        name: "{{ item.name }}"
        password: "{{ item.pass | password_hash('sha512') }}"
      loop: "{{ usuarios }}"
