---
- name: Control de errores. Failed When
  hosts: rhel

  tasks:
    - name: Localizar directorio temporal
      ansible.builtin.command:
        cmd: ls -l /temporal
      register: salida
      failed_when: salida.rc == 0

    - name: visualizar salida
      ansible.builtin.debug:
        var: salida
