# when CONDICIONAL BASICO DE Ansible, SE TRATA DE UNA EXPRESION JINJA2, NO SE UTILIZAN DOBLES LLAVES Y SDE EVALUA PARA TODOS LOS HOSTS

# OPERADORES HABITUALES: < > >= <= !=
# LA COMPARACION ES CON ==
# "is defined" PERMITE SABER SI UNA VARIABLE EXISTE
# "not" PERMITE USAR LA NEGACION
# PARA BUSCAR EN UN ARRAY SE PUEDE USAR EL OPERADOR "in"

---
- name: Prueba con WHEN. visualizar la fecha en los debian
  hosts: all
  tasks:
    - name: Capturar fecha
      ansible.builtin.shell:
        cmd: date
      register: fecha
      when: ansible_distribution == 'Debian'

    - name: Visuzalizar fecha
      ansible.builtin.debug:
        msg: "{{ fecha.stdout}}"
      when: ansible_distribution == 'Debian'

- name: Prueba con WHEN. visualizar la fecha en los debian o rocky
  hosts: all
  tasks:
    - name: Capturar fecha
      ansible.builtin.shell:
        cmd: date
      register: fecha
      when: ansible_distribution == 'Debian' || ansible_facts['distribution'] == 'Rocky'

    - name: Visuzalizar fecha
      ansible.builtin.debug:
        msg: "{{ fecha.stdout}}"
      when: ansible_distribution == 'Debian' || ansible_facts['distribution'] == 'Rocky'

############################# when CON VARIABLES ##################################

- name: Prueba con WHEN. Uso con Variables
  hosts: debian1
  vars:
    ejecutar: True
  tasks:
    - name: Instalar GIT
      ansible.builtin.apt:
        name: git
        state: latest
      when: ejecutar == True
      #when: not ejecutar
######################### when CON VARIABLES REGISTRADAS #######################
- name: Prueba con WHEN. Crear un fichero en un directorio si esta vacio
  hosts: debian1
  tasks:
    - name: Ver si el directorio esta vacio
      ansible.builtin.command:
        cmd: ls /tmp/dir1
      register: resultado

    - name: Crear un fiechero si no existe nada el el directorio
      ansible.builtin.file:
        path: /tmp/dir1/f1.txt
        state: touch:
      when: resultado.stdout == ""


################################3 ACTUALIZAR UN PAQUETE DE PHP CON when ##############################3333
- name: Prueba con when. INSTALAR PHP ANTIGUO
  hosts: ubuntu1
  tasks:
    - name: Instalar gpg
      ansible.builtin.apt:
        name: gpg
        state: latest

    - name: Actualizar repositorio de phph
      ansible.builtin.shell:
        cmd: add-apt-repository ppa:ondrej/php -y

    - name: Actualizar cache apt
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true
      
    - name: Instalar version antigua de PHP
      ansible.builtin.apt: 
        name: php7.4
      

- name: Comprobar version de PHP
  ansible.builtin.shell:
    cmd: php -v | php --version | head -n 1 | cut -c 5-10
  register: resultado

- name: Viosualizar resultado. Solo como ejemplo
  ansible.builtin.debug:
    msg: "{{ resultado.stdout  }}"
  when: resultado.stdout != "8.1.17"

- name: Actualizar PHP
  ansible.builtin.apt:
    name: php8.1
  when: resultado.stdout != "8.1.17"

- name: