---
- name: Prueba con Variables Registradas
  hosts: rhel1
  tasks:
    - name: Capturar fecha
      ansible.builtin.shell:
        cmd: date
      register: fecha

    - name: Mostrar fecha
      ansible.builtin.debug:
        var: fecha.stdout

    - name: Mostrar fecha
      ansible.builtin.debug:
        msg: "{{ fecha.stdout }}"
