---
- name: prueba con variables
  hosts: debian1
  vars:
    - mensaje: "esto es otro mensaje ansible"
    - curso: "dentro curso ansible"
    - desarrollo:
        tipo: linux
        memoria: 4GB
        disco: 500GB
  tasks:
    - name: ver variables
      debug:
        msg: los ordenadores de desarrollo son: "{{ desarrollo }} y su memoria es {{ desarrollo.memoria }} {{ desarrollo['memoria'] }}"
