# PERMITE CREAR VARIABLES DINAMICAS
---
- name: Probar con set_fact
  hosts: debian1
  tasks:
    - name: crear una variable
      set_fact:
        fichero: desarrollo.txt

    - name: Crear el fichero en la maquina
      ansible.builtin.file:
        path: "/tmp/{{ fichero }}"
        state: touch
    - name: Crear una variable con una expresion
      set_fact:
        nombre: "{{ ansible_facts }}['hostname'] | upper"

    - name: Visualizar el nombre de la maquina
      ansible.builtin.debug:
        msg: El nombre en mayusuclas es "{{ nombre }}"
